
runtime: nodejs
vm: true
instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1   #automatic  # default value
  min_pending_latency: 100ms  # default value
  max_pending_latency: 500ms
  max_concurrent_requests: 50
